In [1]:
#!/bin/python3

import math
import os
import random
import re
import sys

### 1. Set .intersection() Operation

In [1]:
num1 = int(input())
li1 = input().split()
num2 = int(input())
li2 = input().split()

li1 = set(li1)
li2 = set(li2)

li3 = li1.intersection(li2)

print(len(li3))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


### 2. Mod Divmod

In [21]:
num1 = int(input())
num2 = int(input())
print('{0}\n{1}'.format(*divmod(num1, num2)))
print(divmod(num1, num2))

177
10
17
7
(17, 7)


### 3. Power - Mod Power

In [27]:
num1 = int(input())
num2 = int(input())
num3 = int(input())
print(pow(num1, num2))
print(pow(num1, num2, num3))

3
4
5
81
1


### 4. Set .difference() Operation

In [39]:
num1 = int(input())
li1 = set(map(int, input().split()))
num2 = int(input())
li2 = set(map(int, input().split()))

li3 = li1.difference(li2)

print(len(li3))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8


### 5. Integers Come In All Sizes

In [52]:
a, b, c, d = (int(input()) for i in range(4))
print(pow(a, b) + pow(c, d))

9
29
7
27
4710194409608608369201743232


### 6. Set .symmetric_difference() Operation

In [54]:
num1 = int(input())
li1 = set(map(int, input().split()))
num2 = int(input())
li2 = set(map(int, input().split()))

li3 = li1.symmetric_difference(li2)

print(len(li3))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8


### 7. Set Mutations

In [114]:
# 7-1
# set.update 합집합
# set.intersection_update 교집합
# set.difference_update 차집합
# set.symmetric_difference_update 차집합

num1 = int(input())
s = set(map(int, input().split(' ')))
num2 = int(input())
for i in range(num2):
    string, num3 = input().split(' ')
    li2 = set(map(int, input().split(' ')))
    eval('s.{0}({1})'.format(string, li2))
print(sum(s))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


### 8. The Captain's Room

In [115]:
# 8-1

from collections import Counter

num = int(input())
arr = list(map(int, input().split()))

ca = Counter(arr)
for i in ca:
    if ca[i] != num:
        print(i)

### 9. Check Subset

In [137]:
# 9-1
# issubset 부분집합

for _ in range(int(input())):
    x, a, z, b = input(), set(input().split()), input(), set(input().split())
    print(a.issubset(b))

1
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True


### 10. Check Strict Superset

In [138]:
# 10-1
# issubset, <, >
# all
a = set(input().split())
print(all(a > set(input().split()) for _ in range(int(input()))))

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


### 11. Class 2 - Find the Torsional Angle

In [144]:
# 11-1
# 나중에 다시 볼것

import math

class Points(object):
    def __init__(self, x, y, z):
        self.x=x
        self.y=y
        self.z=z

    def __sub__(self, no):
        return  Points((self.x-no.x),(self.y-no.y),(self.z-no.z))

    def dot(self, no):
        return (self.x*no.x)+(self.y*no.y)+(self.z*no.z)

    def cross(self, no):
        return Points((self.y*no.z-self.z*no.y),(self.z*no.x-self.x*no.z),(self.x*no.y-self.y*no.x))
        
    def absolute(self):
        return pow((self.x ** 2 + self.y ** 2 + self.z ** 2), 0.5)
if __name__ == '__main__':
    points = list()
    for i in range(4):
        a = list(map(float, input().split()))
        points.append(a)

    a, b, c, d = Points(*points[0]), Points(*points[1]), Points(*points[2]), Points(*points[3])
    x = (b - a).cross(c - b)
    y = (c - b).cross(d - c)
    angle = math.acos(x.dot(y) / (x.absolute() * y.absolute()))

    print("%.2f" % math.degrees(angle))

0 4 5
1 7 6
0 5 9
1 7 2
8.19


### 12. Zipped!

In [ ]:
5 3
89 90 78 93 80
90 91 85 88 86  
91 92 83 89 90.5

In [12]:
a, b = map(int, input().split(' '))

li = []

for j in range(b):
    li.append(list(map(float, input().split())))

X = zip(*li)
X = list(X)

for i in range(len(X)):
    print(sum(X[i])/len(X[i]))

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


### 13. Input()

In [ ]:
# 13-1
# eval
# (x**3 + x**2 + x + 1) == 4

ui = input().split()
x = int(ui[0])
print(eval(input()) == int(ui[1]))


### 14. Python Evaluation

In [23]:
# 14-1

eval(input())

5


### 15. Any or All

In [24]:
# 15-1
# 이해가 잘 안감

N = int(input())
n = input().split()
print(all([int(i)>0 for i in n]) and any([j == j[::-1] for j in n]))

True

### 16. Detect Floating Point Number

In [43]:
# 16-1
# regrex 나중에 제대로 공부

import re

for _ in range(int(input())):
    print(bool(re.match(r'^[-+]?[0-9]*\.[0-9]+$', input())))

4
4.0O0
False
-1.00
True
+4.54
True
SomeRandomStuff
False


### 17. Map and Lambda Function

In [64]:
# 17-1
# lambda 좀 더 공부가 필요함
# 피보나치
# 다양한 테스트 케이스들을 해보자

cube = lambda x:pow(x,3)

def fibonacci(n):
    li = [0, 1]
    for i in range(2, n):
        li.append(li[-2]+li[-1])
    return li[0:n]

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

1
[0]


### 18. Re.split()

In [69]:
# 18-1
# regex 공부 많이 필요함!!

regex_pattern = r"\D+"

import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


### 19. Group(), Groups() & Groupdict()

In [94]:
# 19-1
# regex - group(), groups(), groupdict()
# 모르겠다... 공부

import re
m = re.search(r'([a-zA-Z0-9])\1+', input().strip())
print(m.group(1) if m else -1)

..12345678910111213141516171820212223
1


### 20. Re.findall() & Re.finditer()

In [107]:
# 20-1
# regex
# findall - 문자만 리스트로
# finditer
# 모르겠다... 공부!

import re
v = "aeiou"
c = "qwrtypsdfghjklzxcvbnm"
m = re.findall(r"(?<=[%s])([%s]{2,})[%s]" % (c, v, c), input(), flags = re.I)
print('\n'.join(m or ['-1']))

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


### 21 Re.start() & Re.end()

In [127]:
# 21-1
# regex
# 공부

import re

S = input()
k = input()

pattern = re.compile(k)
r = pattern.search(S)
if not r: print("(-1, -1)")
while r:
    print("({0}, {1})".format(r.start(), r.end() - 1))
    r = pattern.search(S,r.start() + 1)

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


### 22. Validating Roman Numerals

In [131]:
# 22-1
# regex
# 공부

import re

thousand = 'M{0,3}'
hundred = '(C[MD]|D?C{0,3})'
ten = '(X[CL]|L?X{0,3})'
digit = '(I[VX]|V?I{0,3})'
print (bool(re.match(thousand + hundred+ten+digit +'$', input())))

CDXXI
True


In [132]:
# 22-2
# regex

regex_pattern =r'^M{,3}(C(D|M)|D?C{,3})(X(L|C)|L?X{,3})(I(X|V)|(X|V)?I{,3})$'
import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


### 23. Validating phone numbers

In [136]:
# 23-1
# regex
# 공부

import re
N=input()
for i in range(int(N)):
    if re.match(r'[789]\d{9}$',input()):   
        print('YES')
    else:  
        print('NO')

2
9587456281
YES
1252478965
NO


### 24. Validating and Parsing Email Addresses

In [139]:
# 24-1
# regex
# 공부

import re
n = int(input())
for _ in range(n):
    x, y = input().split(' ')
    m = re.match(r'<[A-Za-z](\w|-|\.|_)+@[A-Za-z]+\.[A-Za-z]{1,3}>', y)
    if m:
        print(x,y)

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


### 25. Hex Color Code

In [142]:
# 25-1
# regex
# 와우... 공부...

import re
pattern=r'(#[0-9a-fA-F]{3,6}){1,2}[^\n ]'
for _ in range(int(input())):
    for x in re.findall(pattern,input()):
        print(x)

11
#BED
{
color: #FfFdF8; background-color:#aef;
#FfFdF8
#aef
font-size: 123px;
background: -webkit-linear-gradient(top, #f9f9f9, #fff);
#f9f9f9
#fff
}
#Cab
{
background-color: #ABC;
#ABC
border: 2px dashed #fff;
#fff
}


### 26. HTML Parser - Part 1

In [145]:
# 26-1
# regex
# 공부

from html.parser import HTMLParser
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):        
        print ('Start :',tag)
        for ele in attrs:
            print ('->',ele[0],'>',ele[1])
            
    def handle_endtag(self, tag):
        print ('End   :',tag)
        
    def handle_startendtag(self, tag, attrs):
        print ('Empty :',tag)
        for ele in attrs:
            print ('->',ele[0],'>',ele[1])
            
MyParser = MyHTMLParser()
MyParser.feed(''.join([input().strip() for _ in range(int(input()))]))

2
<html><head><title>HTML Parser - I</title></head>
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


### 27. HTML Parser - Part 2

In [146]:
# 27 - 1
# regex
# 공부

from html.parser import HTMLParser
class CustomHTMLParser(HTMLParser):
    def handle_comment(self, data):
        number_of_line = len(data.split('\n'))
        if number_of_line>1:
            print('>>> Multi-line Comment')
        else:
            print('>>> Single-line Comment')
        if data.strip():
            print(data)

    def handle_data(self, data):
        if data.strip():
            print(">>> Data")
            print(data)

parser = CustomHTMLParser()

n = int(input())

html_string = ''
for i in range(n):
    html_string += input().rstrip()+'\n'
    
parser.feed(html_string)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


### 28. Detect HTML Tags, Attributes and Attribute Values

In [147]:
# 28-1
# regex
# 공부

from html.parser import HTMLParser
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        [print('-> {} > {}'.format(*attr)) for attr in attrs]
        
html = '\n'.join([input() for _ in range(int(input()))])
parser = MyHTMLParser()
parser.feed(html)
parser.close()

9
<head>
<title>HTML</title>
</head>
<object type="application/x-flash" 
  data="your-file.swf" 
  width="0" height="0">
  <!-- <param name="movie" value="your-file.swf" /> -->
  <param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


### 29. XML 1 - Find the Score

In [ ]:
# 29-1
# XML
# 공부

import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    return sum([len(elem.items()) for elem in tree.iter()])

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

### 30. Validating UID

In [159]:
# 30-1
import re

for _ in range(int(input())):
    u = ''.join(sorted(input()))
    try:
        assert re.search(r'[A-Z]{2}', u)
        assert re.search(r'\d\d\d', u)
        assert not re.search(r'[^a-zA-Z0-9]', u)
        assert not re.search(r'(.)\1', u)
        assert len(u) == 10
    except:
        print('Invalid')
    else:
        print('Valid')

2
B1CD102354
Invalid
B1CDEF2354
Valid


### 31. XML2 - Find the Maximum Depth

In [161]:
# 31-1
# XML
# 공부

import xml.etree.ElementTree as etree

maxdepth = -1
def depth(elem, level):
    global maxdepth
    if (level == maxdepth):
        maxdepth += 1
        
    for child in elem:
        depth(child, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
    <title>HackerRank</title>
    <subtitle lang='en'>Programming challenges</subtitle>
    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
    <updated>2013-12-25T12:00:00</updated>
</feed>
1


### 32. Standardize Mobile Number Using Decorators

In [168]:
# 32-1
# decorator
# 공부

def wrapper(f):
    def fun(l):
        f(["+91 " + c[-10:-5] + " " + c[-5:] for c in l])
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


### 33. Decorators 2 - Name Directory

In [170]:
# 33-1
# decorator
# yield
# itemgetter
# 공부!!!

import operator

def person_lister(f):
    def inner(people):
        # complete the function
        for ps in sorted(people, key=lambda x: int(x[2])):
            yield f(ps)
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


### 34. Arrays

In [198]:
# 34-1
# sorted아니고 reverse.. 문제 조건 잘 확인하기

import numpy

def arrays(arr):
    ar = numpy.array(arr[::-1], float)
    return ar

arr = input().strip().split(' ')
result = arrays(arr)
print(result)
print(type(result[0]))

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]
<class 'numpy.float64'>


### 35. Shape and Reshape

In [238]:
# 35-1
# shape, reshape
# Sample Input 값 잘 확인

import numpy as np
print(np.array(input().split(' '), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 36. Transpose and Flatten

In [268]:
# 36-1
# transpose
# flatten

import numpy as np

n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print(array.transpose())
print(array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### 37. Concatenate

In [302]:
# 37-1
# concatenate

import numpy as np

a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)], int)
arrB = np.array([input().split() for _ in range(b)], int)
print(np.concatenate((arrA, arrB), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### 38. Zeros and Ones

In [331]:
# 38-1
# zeros
# ones

nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, int))
print (numpy.ones(nums, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### 39. Eye and Identity

In [353]:
# 39-1
# identify - 정방단위행렬, 단위행렬은 대각행렬이 1이고 나머지는 모두 0인 행렬
# eye
# replace (str)

import numpy

n, m = map(int, input().split())
print(str(numpy.eye(n, m)).replace('1', ' 1').replace('0', ' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 40. Array Mathematics

In [383]:
# 40-1
# 잘 이해가 안감
# 공부

import numpy as np

n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### 41. Floor, Ceil and Rint

In [20]:
# 41-1
# floor - 내림
# ceil - 올림
# rint - 반올림
# set_printoptions - numpy 출력 옵션
# 출력 결과물 띄어쓰기 잘 보자

import numpy

numpy.set_printoptions(sign=' ')
a = numpy.array(input().split(), float)
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### 42. Sum and Prod

In [35]:
# 42-1
# sum
# prod

import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24


### 43. Min and Max

In [42]:
# 43-1
# sample input 라인별로 줄 의미 확인. 특히 첫째줄

import numpy

arr=[]
n,m=map(int,input().split())

for row in range(n):
    my_arr=list(map(int,input().split()))
    arr.append(my_arr)

my_array=numpy.array(arr)
result=numpy.min(my_array, axis = 1)

print(max(result))

4 2
2 5
3 7
1 3
4 0
3


### 44. Mean, Var, and Std


In [59]:
# 44-1
# mean - 평균
# var - 분산
# std - 표준편차
# 출력 - 소수점 자리수 확인
# 뭔가 이상하다..

import numpy

numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
my_array = numpy.array([input().split() for _ in range(N)], int)

print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(numpy.std(my_array, axis = None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [65]:
# 44-2
# 1번답은 hackerrank에서 통과가 안됨.. 출력부분 띄어쓰기..
# 2번답은 됨.. 차이를 모르겠다

import numpy
array = []
n, m = map(int, input().split())
for _ in range(n): array.append(list(map(int, input().split())))
array = numpy.array(array)
print(numpy.mean(array, axis=1))
print(numpy.var(array, axis=0))
print(round(numpy.std(array), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### 45. Dot and Cross

In [81]:
# 45-1
# dot - 행렬곱
# cross - 백터곱
# 백터곱 공부

import numpy

a = int(input())

arr1 = numpy.array([list(map(int,input().split())) for _ in range(a)])
arr2 = numpy.array([list(map(int,input().split())) for _ in range(a)])

print(numpy.dot(arr1, arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### 46. Inner and Outer

In [84]:
# 46-1
# inner, outer
# 공부

import numpy as np

A = np.array(input().split(), int)
B = np.array(input().split(), int)

print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


### 47. Polynomials

In [97]:
# 47-1
# polynomials - 다항식
# poly
# roots
# polyint
# polyder
# polyval
# polyfit
# 공부

print(__import__('numpy').polyval(list(map(float,input().split())),float(input())))

1.1 2 3
0
3.0


### 48. Linear Algebra

In [98]:
# 48-1
# linalg.det
# linalg.eig
# linalg.inv
# 공부...

import numpy

print(round(numpy.linalg.det(numpy.array([list(map(float,input().split())) for _ in range(int(input()))])),2))


2
1.1 1.1
1.1 1.1
0.0
